workflows:
  ios-native-workflow:
    name: iOS Native
    environment:
       groups:
           - manual_code_signing
       vars:
        XCODE_SCHEME: "MVVM-Example"  
        XCODE_PROJECT: "MVVM-Example" 
       xcode: 15.0
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*master'
          include: true
          source: true
    scripts:
     - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
       script: |
        keychain initialize
     - name: set up provisioning profiles
       script: |
            PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
            mkdir -p "$PROFILES_HOME"
            PROFILE_PATH="$(mktemp "$PROFILES_HOME"/$(uuidgen).mobileprovision)"
            echo ${CM_PROVISIONING_PROFILE} | base64 --decode > $PROFILE_PATH
            echo "Saved provisioning profile $PROFILE_PATH"  
     - name: Add signing certificate to keychain
       script: |
            echo "start process"
            echo $CM_CERTIFICATE | base64 --decode > /tmp/certificate.p12
            echo "CM_CERTIFICATE decode"

            if [ -n "$CM_CERTIFICATE_PASSWORD" ]; then
              echo CM_CERTIFICATE_PASSWORD found is $CM_CERTIFICATE_PASSWORD
              keychain add-certificates -c /tmp/certificate.p12 --certificate-password $CM_CERTIFICATE_PASSWORD    
            else
              echo "CM_CERTIFICATE_PASSWORD not find"
              keychain add-certificates -c /tmp/certificate.p12     
            fi
     - name: Build App
       script: |
            xcodebuild clean build -project $XCODE_PROJECT" -scheme "$XCODE_SCHEME" -sdk iphoneos -destination generic/platform=iOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
     - name: iOS test
       script: |
            xcode-project run-tests \
             --project "$XCODE_PROJECT" \
             --scheme "$XCODE_SCHEME" \
             --device "iPhone 15 Pro"
     - name: iOS UItest
       script: |
            xcode-project run-tests \
             --project "$XCODE_PROJECT" \
              --scheme "$XCODE_SCHEME" \
              --device "iPhone 15 Pro"
     - name: Set up code signing settings on Xcode project
       script: xcode-project use-profiles
     - name: Build .ipa
       script: xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"