workflows:
  ios-native-workflow:
    name: iOS Native
    environment:
      vars:
        XCODE_SCHEME: "MVVM-Example"  
        XCODE_PROJECT: "MVVM-Example" 
    scripts:
     - name: Build App
       script: |
          xcodebuild build -project "$XCODE_PROJECT.xcodeproj" - scheme "$XCODE_SCHEME" XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED "NO"
     - name: iOS test
       script: |
        xcode-project run-tests \
          --project mvvm-demo \
          --scheme MVVM-ExampleTests \
          --device "iPhone 15"