workflows:
  ios-native-workflow:
    name: iOS Native
    environment:
      vars:
        XCODE_SCHEME: "MVVM-Example"  
        XCODE_PROJECT: "MVVM-Example" 
    scripts:
     - name: Build App
       script: |
        xcodebuild clean build -project "MVVM-Example.xcodeproj" -scheme "MVVM-Example" -sdk iphoneos -destination generic/platform=iOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
     - name: iOS test
       script: |
        xcodebuild \
            test \
            -project MVVM-Example.xcodeproj \
            -scheme MVVM-ExampleTests \
            -destination 'platform=iOS,OS=17.0,name=iPhone 15 Pro'