workflows:
  ios-native-workflow:
    name: iOS Native
    environment:
      vars:
        XCODE_SCHEME: "MVVM-Example"  
        XCODE_PROJECT: "MVVM-Example" 
    scripts:
     - name: Build App
       script: |
        xcodebuild clean build -project "MVVM-Example.xcodeproj" -scheme "MVVM-Example" -sdk iphoneos -destination generic/platform=iOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
     - name: iOS test
       script: |
        xcode-project run-tests \
          --project mvvm-demo \
          --scheme MVVM-ExampleTests \
          --device "iPhone 15"